version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    container_name: els
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.4
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - XPACK_SECURITY_ENABLED=false
      - XPACK_FLEET_ENABLED=false
      - XPACK_STREAMS_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=dev-encrypted-saved-objects-key-aaaaaaaaaaaaaaaaaaaaaa
      - XPACK_SECURITY_ENCRYPTIONKEY=dev-security-session-key-bbbbbbbbbbbbbbbbbbbbbbbb
      - XPACK_REPORTING_ENCRYPTIONKEY=dev-reporting-key-cccccccccccccccccccccccc
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
